"""Install-side helpers: expose the skill to Hermes, schedule a monitor.

Two small jobs, both about closing the gap between "a plugin is installed" and
"the agent actually uses it":

``install_skill``
    A skill registered through ``ctx.register_skill`` is namespaced and
    **explicit-load only** — it never appears in the agent's
    ``<available_skills>`` list, so it cannot auto-trigger. Copying the same
    ``SKILL.md`` into ``$HERMES_HOME/skills/productivity/job-reach/`` makes it
    discoverable like any other skill. The copy is deliberately a plain file,
    regenerated on demand, so a plugin update simply overwrites it.

``install_cron``
    Wires the recurring "what's new?" run into Hermes' own scheduler instead of
    shipping a second scheduler (the original project embedded APScheduler;
    Hermes already has a cron system with delivery to every chat platform).
    The job uses monitor mode, so an unchanged board never wakes the model. The
    monitor script it generates is Python (see :func:`install_monitor_script`),
    which is what makes the feature work on Windows too.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .config import hermes_home, plugin_dir
from .errors import ConfigError
from .logging_setup import get_logger
from .platforms import is_windows
from .runtime import engine_argv

logger = get_logger("install")

#: Where the auto-discoverable copy of the skill lives.
SKILL_CATEGORY = "productivity"
SKILL_NAME = "job-reach"

#: Bundled skill directory inside the plugin.
BUNDLED_SKILL = Path("skills") / "job-search"

MONITOR_SCRIPT_NAME = "job-reach-monitor.py"

#: The generated cron monitor. Kept as a template (not a bash heredoc) so the
#: same file works on every platform Hermes supports — see
#: :func:`install_monitor_script`.
MONITOR_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by the job-reach Hermes plugin — do not edit by hand.

Prints a byte-stable digest of NEW job listings on stdout. Empty output means
"nothing changed", which is how `hermes cron` suppresses a redundant agent run.

It runs under whichever interpreter Hermes uses for cron scripts, and starts the
job-reach engine itself — with the plugin directory on PYTHONPATH and the
interpreter that owns the scraping stack (see jobreach.runtime).
"""

import os
import subprocess
import sys

PLUGIN_DIR = {plugin!r}
ENGINE = {python!r}
ARGS = {args!r}


def main() -> int:
    env = dict(os.environ)
    env["PYTHONPATH"] = PLUGIN_DIR
    env.pop("VIRTUAL_ENV", None)
    completed = subprocess.run(
        [ENGINE, "-m", "jobreach", "monitor", *ARGS],
        cwd=PLUGIN_DIR,
        env=env,
        capture_output=True,
        text=True,
    )
    sys.stdout.write(completed.stdout or "")
    sys.stderr.write(completed.stderr or "")
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
'''


DEFAULT_CRON_PROMPT = """\
The job-reach monitor reported changed output: the Japanese job boards you
watch have new listings since the last check.

Do this:
1. Run the `job_search` tool for the same query (new_only=true) to get the
   structured result, or use the `job-reach:job-search` skill for the full
   procedure.
2. Write an Obsidian note with `job_note` so the run is persisted.
3. Reply with a short digest, grouped by board, newest and most relevant
   first: title, company, location, link. Flag genuinely new listings.
4. Reply in the language the user writes in (Russian or English).

If a board failed this run, say which one and why instead of staying silent.
Never invent listings: if a board returned nothing, report zero.
"""


def skills_root() -> Path:
    """Hermes' user skills directory."""
    return hermes_home() / "skills"


def scripts_root() -> Path:
    """Hermes' user scripts directory (``hermes cron --script`` reads here)."""
    root = hermes_home() / "scripts"
    root.mkdir(parents=True, exist_ok=True)
    return root


def install_skill(*, force: bool = True) -> Path:
    """Copy the bundled skill into Hermes' skills tree. Returns the SKILL.md path."""
    source_dir = plugin_dir() / BUNDLED_SKILL
    source = source_dir / "SKILL.md"
    if not source.exists():  # pragma: no cover - packaging error
        raise ConfigError(f"bundled skill is missing at {source}")

    target_dir = skills_root() / SKILL_CATEGORY / SKILL_NAME
    if target_dir.exists() and not force:
        return target_dir / "SKILL.md"
    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target_dir / "SKILL.md")

    # Ship the skill's supporting references alongside it.
    for extra in ("references", "scripts", "assets"):
        src = source_dir / extra
        if src.is_dir():
            dst = target_dir / extra
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst)

    logger.info("skill installed", extra={"path": str(target_dir / "SKILL.md")})
    return target_dir / "SKILL.md"


def install_monitor_script(extra_args: list[str] | None = None) -> Path:
    """Write the cron monitor script into Hermes' scripts directory.

    The script is **Python, not bash**, and that is a portability decision:
    Hermes runs a cron script by its extension — ``.sh``/``.bash`` go through
    bash (absent on a stock Windows install), everything else through Hermes'
    own interpreter. A Python monitor therefore behaves identically on macOS,
    Linux and Windows, where the old ``#!/usr/bin/env bash`` version needed Git
    Bash on Windows.

    The search arguments are baked into the script rather than passed on the
    cron command line, because ``hermes cron --monitor-script`` accepts a bare
    path with no arguments.
    """
    python = engine_argv()[0]
    plugin = plugin_dir()
    target = scripts_root() / MONITOR_SCRIPT_NAME
    args = [str(part) for part in (extra_args or [])]

    # str(), not the Path objects themselves: repr() of a Path is not Python
    # source (``PosixPath('…')`` raises NameError in the generated script).
    body = MONITOR_SCRIPT_TEMPLATE.format(plugin=str(plugin), python=str(python), args=args)
    target.write_text(body, encoding="utf-8")
    if os.name != "nt":  # the executable bit is meaningless on Windows
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def install_cron(
    *,
    schedule: str = "0 9 * * *",
    keyword: str | None = None,
    location: str = "tokyo",
    sources: str = "wantedly,linkedin",
    deliver: str | None = None,
    name: str = "job-reach-monitor",
    prompt: str = DEFAULT_CRON_PROMPT,
) -> dict[str, Any]:
    """Create a Hermes cron job that watches the boards and reports changes."""
    hermes = shutil.which("hermes")
    if hermes is None:
        raise ConfigError(
            "the `hermes` executable is not on PATH, so the cron job cannot be "
            "created from here; run the printed command manually"
        )

    monitor_args: list[str] = []
    if keyword:
        monitor_args += ["--keyword", keyword]
    monitor_args += ["--location", location, "--source", sources]
    monitor = install_monitor_script(monitor_args)

    command = [
        hermes, "cron", "create", schedule, prompt,
        "--name", name,
        "--monitor-script", str(monitor),
        "--skill", "job-reach:job-search",
        "--workdir", str(plugin_dir()),
    ]
    if deliver:
        command += ["--deliver", deliver]

    result = subprocess.run(command, capture_output=True, text=True)
    created = result.returncode == 0
    message = (
        f"Cron job {name!r} created: {schedule}"
        if created
        else f"Could not create the cron job: {(result.stderr or result.stdout).strip()[:400]}"
    )
    return {
        "created": created,
        "name": name,
        "schedule": schedule,
        "monitor_script": str(monitor),
        "command": command_line(command),
        "message": message,
        "stdout": result.stdout.strip()[:1000],
    }


def _quote(value: str) -> str:
    """Minimal shell quoting for POSIX command lines."""
    if value and all(ch.isalnum() or ch in "._-/:=" for ch in value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def command_line(argv: Sequence[str]) -> str:
    """A **runnable** one-line form of *argv* on this platform.

    The plugin prints commands for a human to paste (when it cannot create a
    cron job itself), so the quoting has to match the shell they will paste into:
    POSIX quoting on macOS/Linux, ``list2cmdline`` on Windows.
    """
    parts = [str(part) for part in argv]
    if is_windows():
        return subprocess.list2cmdline(parts)
    return " ".join(_quote(part) for part in parts)


def hermes_env_hint() -> str:
    """Message shown when Hermes' home cannot be located."""
    return f"HERMES_HOME={os.environ.get('HERMES_HOME', '(unset)')}"
