"""Install-side helpers: expose the skill to Hermes, schedule a monitor.

Two small jobs, both about closing the gap between "a plugin is installed" and
"the agent actually uses it":

``install_skill``
    A skill registered through ``ctx.register_skill`` is namespaced and
    **explicit-load only** — it never appears in the agent's
    ``<available_skills>`` list, so it cannot auto-trigger. Copying the same
    ``SKILL.md`` into ``$HERMES_HOME/skills/productivity/job-reach/`` makes it
    discoverable like any other skill. The copy is deliberately a plain file,
    regenerated on demand, so a plugin update simply overwrites it.

``install_cron``
    Wires the recurring "what's new?" run into Hermes' own scheduler instead of
    shipping a second scheduler (the original project embedded APScheduler;
    Hermes already has a cron system with delivery to every chat platform).
    The job uses monitor mode, so an unchanged board never wakes the model. The
    monitor script it generates is Python (see :func:`install_monitor_script`),
    which is what makes the feature work on Windows too.
"""

from __future__ import annotations

import json
import os
import shutil
import stat
import subprocess
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .config import hermes_home, plugin_dir
from .errors import ConfigError
from .logging_setup import get_logger
from .platforms import is_windows
from .proc import run_captured
from .runtime import engine_argv

logger = get_logger("install")

#: Where the auto-discoverable copy of the skill lives.
SKILL_CATEGORY = "productivity"
SKILL_NAME = "job-reach"

#: Bundled skill directory inside the plugin.
BUNDLED_SKILL = Path("skills") / "job-search"

MONITOR_SCRIPT_NAME = "job-reach-monitor.py"

#: Ceiling for creating a cron job through hermes CLI. Bounded so a stuck Hermes
#: cannot wedge the tool call until the outer bridge timeout.
CRON_CREATE_TIMEOUT = 60.0

#: The generated cron monitor. Kept as a template (not a bash heredoc) so the
#: same file works on every platform Hermes supports — see
#: :func:`install_monitor_script`.
MONITOR_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by the job-reach Hermes plugin — do not edit by hand.

Prints a byte-stable digest of NEW job listings on stdout. Empty output means
"nothing changed", which is how `hermes cron` suppresses a redundant agent run.

It runs under whichever interpreter Hermes uses for cron scripts, and starts the
job-reach engine itself — with the plugin directory on PYTHONPATH and the
interpreter that owns the scraping stack (see jobreach.runtime).
"""

import os
import subprocess
import sys

PLUGIN_DIR = {plugin!r}
ENGINE = {python!r}
ARGS = {args!r}
JOB_NAME = {job_name!r}

#: What to tell a user whose monitor script can no longer run. `hermes cron
#: remove` takes the job **id** (not the name), which `hermes cron list` prints.
REMEDY = (
    "re-run `jobreach install-cron` to regenerate this script, or remove the job "
    "`" + JOB_NAME + "` (find its id with `hermes cron list`, then `hermes cron remove <id>`)"
)


def main() -> int:
    if not os.path.exists(ENGINE):
        sys.stderr.write(
            "job-reach monitor: engine interpreter not found at " + str(ENGINE) + "; " + REMEDY + "\\n"
        )
        return 1

    # Preference for the installed copy over the baked one is deliberate:
    # Hermes' tools run the installed snapshot ($HERMES_HOME/plugins/job-reach),
    # so the cron monitor must run the same code the agent does — one update
    # path (rsync), not two truths (today the repo was baked in while the tools
    # used the snapshot).
    candidates = []
    env_dir = os.environ.get("JOBREACH_PLUGIN_DIR")
    if env_dir:
        candidates.append(env_dir)

    hermes_home = os.environ.get("HERMES_HOME")
    if hermes_home:
        candidates.append(os.path.join(hermes_home, "plugins", "job-reach"))
    else:
        candidates.append(os.path.expanduser("~/.hermes/plugins/job-reach"))

    if PLUGIN_DIR not in candidates:
        candidates.append(PLUGIN_DIR)

    plugin_dir = None
    for candidate in candidates:
        if candidate and os.path.exists(os.path.join(candidate, "jobreach", "__main__.py")):
            plugin_dir = candidate
            break

    if not plugin_dir:
        tried = ", ".join(candidates)
        sys.stderr.write(
            "job-reach monitor: plugin directory not found (tried: " + tried + "); " + REMEDY + "\\n"
        )
        return 1

    env = dict(os.environ)
    env["PYTHONPATH"] = plugin_dir
    env.pop("VIRTUAL_ENV", None)
    try:
        completed = subprocess.run(
            [ENGINE, "-m", "jobreach", "monitor", *ARGS],
            cwd=plugin_dir,
            env=env,
            capture_output=True,
            text=True,
        )
    except OSError as exc:
        sys.stderr.write("job-reach monitor: failed to run engine: " + str(exc) + "\\n")
        return 1

    sys.stdout.write(completed.stdout or "")
    sys.stderr.write(completed.stderr or "")
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
'''


DEFAULT_CRON_PROMPT = """\
The job-reach monitor reported changed output: the Japanese job boards you
watch have new listings since the last check.

Do this:
1. Run the `job_search` tool for the same query (new_only=true) to get the
   structured result, or use the `job-reach:job-search` skill for the full
   procedure.
2. Write an Obsidian note with `job_note` so the run is persisted.
3. Reply with a short digest, grouped by board, newest and most relevant
   first: title, company, location, link. Flag genuinely new listings.
4. Reply in the language the user writes in (Russian or English).

If a board failed this run, say which one and why instead of staying silent.
Never invent listings: if a board returned nothing, report zero.
"""


def skills_root() -> Path:
    """Hermes' user skills directory."""
    return hermes_home() / "skills"


def scripts_root() -> Path:
    """Hermes' user scripts directory (``hermes cron --script`` reads here)."""
    root = hermes_home() / "scripts"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _parse_disabled_skills(content: str) -> list[str]:
    """Parse skills.disabled list from config.yaml text without third-party YAML parser."""
    lines = content.splitlines()
    in_skills = False
    in_disabled_block = False
    disabled_indent = 0
    disabled_skills: list[str] = []

    for raw_line in lines:
        line_no_comment = raw_line.split("#", 1)[0].rstrip()
        stripped = line_no_comment.strip()
        if not stripped:
            continue

        indent = len(line_no_comment) - len(line_no_comment.lstrip())

        if indent == 0:
            if stripped == "skills:" or stripped.startswith("skills:"):
                in_skills = True
                in_disabled_block = False
                continue
            else:
                if in_skills:
                    break
                continue

        if not in_skills:
            continue

        if in_disabled_block:
            if indent > disabled_indent and stripped.startswith("-"):
                item = stripped[1:].strip().strip("\"'")
                if item:
                    disabled_skills.append(item)
                continue
            else:
                in_disabled_block = False

        if stripped.startswith("disabled:"):
            rest = stripped[len("disabled:"):].strip()
            if rest.startswith("[") and rest.endswith("]"):
                items_str = rest[1:-1].strip()
                if items_str:
                    for part in items_str.split(","):
                        part_clean = part.strip().strip("\"'")
                        if part_clean:
                            disabled_skills.append(part_clean)
                in_disabled_block = False
            elif not rest:
                in_disabled_block = True
                disabled_indent = indent
            else:
                in_disabled_block = False

    return disabled_skills


def disabled_skill_warning(skill_name: str = SKILL_NAME) -> str | None:
    """Say so when Hermes has this skill switched off in ``config.yaml``.

    ``install_skill`` copies ``SKILL.md`` onto disk, and Hermes then ignores it
    when the name sits under ``skills.disabled``: the copy succeeds, the tool
    reports success, and the skill never triggers. Nothing else can notice that,
    so this is where it gets said.

    Both the directory-derived name (``job-reach``) and the skill's own
    frontmatter name (``job-search``) are matched, because ``skills config``
    lists whichever one Hermes keys on.

    Returns ``None`` — "say nothing" — when ``config.yaml`` is missing or
    unreadable, and when its shape is not one this stdlib-only scan recognises.
    Guessing wrong here would put a permanent false warning in the install path.
    """
    config_path = hermes_home() / "config.yaml"
    try:
        content = config_path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.debug("could not read config", extra={"path": str(config_path), "error": str(exc)})
        return None

    targets = {skill_name, SKILL_NAME, "job-search"}
    for item in _parse_disabled_skills(content):
        if item in targets:
            return (
                f"Skill {item!r} is listed under `skills.disabled` in {config_path}, so "
                "Hermes will not load or trigger it. Remove it from `skills.disabled` "
                "under `skills:` in config.yaml, or change it with `hermes skills config`."
            )
    return None


def install_skill(*, force: bool = True) -> Path:
    """Copy the bundled skill into Hermes' skills tree. Returns the SKILL.md path."""
    source_dir = plugin_dir() / BUNDLED_SKILL
    source = source_dir / "SKILL.md"
    if not source.exists():  # pragma: no cover - packaging error
        raise ConfigError(f"bundled skill is missing at {source}")

    target_dir = skills_root() / SKILL_CATEGORY / SKILL_NAME
    if target_dir.exists() and not force:
        return target_dir / "SKILL.md"
    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target_dir / "SKILL.md")

    # Ship the skill's supporting references alongside it.
    for extra in ("references", "scripts", "assets"):
        src = source_dir / extra
        if src.is_dir():
            dst = target_dir / extra
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst)

    logger.info("skill installed", extra={"path": str(target_dir / "SKILL.md")})
    return target_dir / "SKILL.md"


def install_monitor_script(
    extra_args: list[str] | None = None,
    *,
    job_name: str = "job-reach-monitor",
) -> Path:
    """Write the cron monitor script into Hermes' scripts directory.

    The script is **Python, not bash**, and that is a portability decision:
    Hermes runs a cron script by its extension — ``.sh``/``.bash`` go through
    bash (absent on a stock Windows install), everything else through Hermes'
    own interpreter. A Python monitor therefore behaves identically on macOS,
    Linux and Windows, where the old ``#!/usr/bin/env bash`` version needed Git
    Bash on Windows.

    The search arguments are baked into the script rather than passed on the
    cron command line, because ``hermes cron --monitor-script`` accepts a bare
    path with no arguments.
    """
    python = engine_argv()[0]
    plugin = plugin_dir()
    target = scripts_root() / MONITOR_SCRIPT_NAME
    args = [str(part) for part in (extra_args or [])]

    # str(), not the Path objects themselves: repr() of a Path is not Python
    # source (``PosixPath('…')`` raises NameError in the generated script).
    body = MONITOR_SCRIPT_TEMPLATE.format(
        plugin=str(plugin),
        python=str(python),
        args=args,
        job_name=str(job_name),
    )
    target.write_text(body, encoding="utf-8")
    if not is_windows():  # the executable bit is meaningless on Windows
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def _find_existing_cron_job(name: str) -> dict[str, Any] | None:
    """Read $HERMES_HOME/cron/jobs.json and look for a job with matching name."""
    jobs_file = hermes_home() / "cron" / "jobs.json"
    if not jobs_file.exists():
        return None
    try:
        content = jobs_file.read_text(encoding="utf-8")
        data = json.loads(content)
        if not isinstance(data, dict):
            logger.debug("jobs.json is not an object: %s", jobs_file)
            return None
        jobs = data.get("jobs")
        if not isinstance(jobs, list):
            logger.debug("jobs.json 'jobs' is not a list: %s", jobs_file)
            return None
        for job in jobs:
            if isinstance(job, dict) and job.get("name") == name:
                return job
    except Exception as exc:
        logger.debug("Could not read cron jobs from %s: %s", jobs_file, exc)
        return None
    return None


def install_cron(
    *,
    schedule: str = "0 9 * * *",
    keyword: str | None = None,
    location: str = "tokyo",
    sources: str | None = None,
    deliver: str | None = None,
    name: str = "job-reach-monitor",
    prompt: str = DEFAULT_CRON_PROMPT,
) -> dict[str, Any]:
    """Create a Hermes cron job that watches the boards and reports changes.

    *sources* is baked into the generated monitor script only when the caller
    actually named the boards. ``None`` — the default — leaves ``--source`` out
    of the script entirely, so each scheduled run resolves the boards through
    ``monitor``'s own settings-backed default. Baking a literal list here would
    silently outrank a ``default_sources`` setting: the user changes which boards
    they want watched, and the cron job they installed earlier keeps polling the
    old set forever.
    """
    hermes = shutil.which("hermes")
    if hermes is None:
        raise ConfigError(
            "the `hermes` executable is not on PATH, so the cron job cannot be "
            "created from here; run the printed command manually"
        )

    monitor_args: list[str] = []
    if keyword:
        monitor_args += ["--keyword", keyword]
    monitor_args += ["--location", location]
    if sources:
        monitor_args += ["--source", sources]
    monitor = install_monitor_script(monitor_args, job_name=name)

    existing_job = _find_existing_cron_job(name)
    if existing_job is not None:
        existing_id = existing_job.get("id")
        existing_info: dict[str, Any] = {}
        for key in ("schedule", "monitor_script", "workdir", "enabled", "deliver"):
            if key in existing_job and existing_job[key] is not None:
                existing_info[key] = existing_job[key]

        existing_sched = existing_job.get("schedule")
        if isinstance(existing_sched, dict):
            existing_expr = existing_sched.get("expr")
        elif isinstance(existing_sched, str):
            existing_expr = existing_sched
        else:
            existing_expr = None

        existing_monitor = existing_job.get("monitor_script")
        existing_workdir = existing_job.get("workdir")
        existing_deliver = existing_job.get("deliver")

        schedule_differs = existing_expr != schedule
        monitor_differs = existing_monitor != MONITOR_SCRIPT_NAME
        workdir_differs = existing_workdir != str(plugin_dir())
        deliver_differs = bool(deliver is not None and existing_deliver != deliver)

        edit_cmd = [hermes, "cron", "edit", str(existing_id)]
        if schedule_differs:
            edit_cmd.extend(["--schedule", schedule])
        if monitor_differs:
            edit_cmd.extend(["--monitor-script", MONITOR_SCRIPT_NAME])
        if workdir_differs:
            edit_cmd.extend(["--workdir", str(plugin_dir())])
        if deliver_differs and deliver:
            edit_cmd.extend(["--deliver", deliver])

        stale = bool(existing_workdir and not os.path.exists(existing_workdir))
        differs = schedule_differs or monitor_differs or workdir_differs or deliver_differs

        if stale:
            message = (
                f"Cron job {name!r} ({existing_id}) has a stale workdir that no longer "
                f"exists on disk ({existing_workdir}); run the edit command to update it"
            )
        elif differs:
            message = (
                f"Cron job {name!r} ({existing_id}) already exists but configuration differs; "
                "run the edit command to update it"
            )
        else:
            message = "already installed and up to date; nothing created"

        cmd_line = command_line(edit_cmd)
        payload = {
            "created": False,
            "reused": True,
            "id": existing_id,
            "name": name,
            "schedule": schedule,
            "monitor_script": str(monitor),
            "command": cmd_line,
            "message": message,
            "hint": (
                "Hermes cron create does not deduplicate by name. "
                f"Run `{cmd_line}` to update this job."
            ),
            "existing": existing_info,
            "stdout": "",
        }
        if stale:
            payload["stale"] = True
        return payload

    # Hermes resolves ``--monitor-script`` *under* its own scripts directory and
    # rejects an absolute path outright ("Script path must be relative to
    # ~/.hermes/scripts/"). The generated script lands in exactly that directory,
    # so the bare filename is the argument that works — and it survives a moved
    # HERMES_HOME, which a baked-in absolute path would not. Older builds only
    # accepted the absolute path, hence the fallback: try the form this Hermes
    # wants, and let the other one try if the first is refused. Re-running
    # `cron create` is safe because a refused create writes nothing.
    command: list[str] = []
    result: subprocess.CompletedProcess[str] | None = None
    for monitor_arg in (MONITOR_SCRIPT_NAME, str(monitor)):
        command = [
            hermes, "cron", "create", schedule, prompt,
            "--name", name,
            "--monitor-script", monitor_arg,
            "--skill", "job-reach:job-search",
            "--workdir", str(plugin_dir()),
        ]
        if deliver:
            command += ["--deliver", deliver]

        try:
            result = run_captured(command, timeout=CRON_CREATE_TIMEOUT)
        except subprocess.TimeoutExpired as exc:
            # Treat a timeout as a failure of this form so a stuck Hermes child
            # never wedges the tool call, and proceed to the fallback form.
            err = (exc.stderr or "").strip() or f"hermes cron create timed out after {int(CRON_CREATE_TIMEOUT)}s"
            result = subprocess.CompletedProcess(command, 124, exc.output or "", err)
            continue
        if result.returncode == 0:
            break

    assert result is not None  # the loop above always runs at least once
    created = result.returncode == 0
    message = (
        f"Cron job {name!r} created: {schedule}"
        if created
        else f"Could not create the cron job: {(result.stderr or result.stdout).strip()[:400]}"
    )
    return {
        "created": created,
        "name": name,
        "schedule": schedule,
        "monitor_script": str(monitor),
        "command": command_line(command),
        "message": message,
        "stdout": result.stdout.strip()[:1000],
    }


def _quote(value: str) -> str:
    """Minimal shell quoting for POSIX command lines."""
    if value and all(ch.isalnum() or ch in "._-/:=" for ch in value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def command_line(argv: Sequence[str]) -> str:
    """A **runnable** one-line form of *argv* on this platform.

    The plugin prints commands for a human to paste (when it cannot create a
    cron job itself), so the quoting has to match the shell they will paste into:
    POSIX quoting on macOS/Linux, ``list2cmdline`` on Windows.
    """
    parts = [str(part) for part in argv]
    if is_windows():
        return subprocess.list2cmdline(parts)
    return " ".join(_quote(part) for part in parts)


def hermes_env_hint() -> str:
    """Message shown when Hermes' home cannot be located."""
    return f"HERMES_HOME={os.environ.get('HERMES_HOME', '(unset)')}"
